name: "イシュー"
description: "イシューを報告する"
body:
  - type: textarea
    attributes:
      label: "概要 - WHY"
      placeholder: "なぜこのイシューが必要なのか"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "概要 - WHAT"
      placeholder: "何をするのか"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "受入基準"
      placeholder: "- [ ] 完了条件1\n- [ ] 完了条件2"

  - type: textarea
    attributes:
      label: "関連課題"
      placeholder: "#123"

  - type: textarea
    attributes:
      label: "備考"
      placeholder: "その他の情報"